### ISSUE TITLE
Page scroll reset when setting pig div to "display: none"

### ISSUE THREAD

**Issue by mrbrahman** [schlosser/pig.js#23]
In the onClickHandler, say I have 

```javascript
var pigOptions = {
  urlForSize: function(imageData, size) {
    //...
  },
  onClickHandler: function(filename) {
    document.getElementById("pig").classList.add("hide");
    // code to show bigger pic of filename here

  },
};
```
corresponding css
```css
.hide{
  display: none;
}
```

... in order to hide the contents of the pig div and show the photo in context, I'm seeing that the scroll event is called, and pig resets the output to the top.

**Comment by schlosser** [comment]
Instead of `display: none`, I'd recommend either putting an opaque layer between the image and the background (I used that technique on [this page](https://schlosser.io/travel/australia-winter-2019/)) or use `opacity:0` depending on your needs.

**Comment by mrbrahman** [comment]
Thanks for the tip! Got it to work with `opacity: 0` and adjusting the top of the photo to be shown using `window.scrollY`.

I looked at the other page you shared, but wasn't able to quite understand what was going on or which elements were used as opaque layer. Do you mind explaining in a few words? Thanks!

**Comment by schlosser** [comment]
Here is the [code for my openViewer function](https://github.com/schlosser/schlosser.io/blob/master/_js/progressive-image.js#L92-L161)

The gist is:
1. figure out where on the page the element is, where it should be in the "viewer" state
2. Apply DOM transitions to scale the picture to full screen
3. Add a class to the body to signal that the scrim (opaque layer) should start to appear. See the [CSS](https://github.com/schlosser/schlosser.io/blob/master/_scss/_progressive.scss#L1-L20) and [HTML](https://github.com/schlosser/schlosser.io/blob/master/_layouts/base.html#L78-L82) for the scrim.
4. Add listeners that close the viewer.

**Comment by mrbrahman** [comment]
Thanks a lot!
