### ISSUE TITLE
Adding and removing images in grid dynamically

### ISSUE THREAD

**Issue by poojakapuriya619** [schlosser/pig.js#26]
Can we add or remove images dynamically in the layout?
Or do we always need to have data for all images? 

Thanks in Advance!

**Comment by schlosser** [comment]
Unfortunately, this isn't possible cleanly. The goal of this library is to be able to provide a smooth scrolling experience, and the tactic is for the library to understand (load metadata for) the entire grid of images. If you have so many images that this isn't possible (more than 10k, for example), you would have to do some pretty major surgery.

The general approach I'd take:

1. create multiple instances of the library, one for each ~10k chunk of images.
2. listen to the scroll position of the first instance. When you get to ~90% of the way down the first instance, load metadata and initialize the second instance, and so on.
