### ISSUE TITLE
Triggering script after pig.enable() has finished?

### ISSUE THREAD

**Issue by mark-rodgers** [schlosser/pig.js#7]
I'll preface this by saying I don't do much work in js, so apologies if this question is basic. And this isn't an issue directly with your library but I'm trying to figure out how I can call another js function that I've written AFTER the enable function finishes and all the pig html structure is in place.

I'm trying to run another script after the pig.js finishes it's stuff so that I can add a lightbox to my images. I tested the lightbox script in the chrome console and it works fine with pig.js but I can't seem to get the code to execute at the right time, I tried putting in a document ready function but the code was still getting called before pig.js finishes adding all the html structure. Resulting in my jQuery selectors returning empty.

Suggestions that you may or may not like but maybe you can include some kind of callback function that can be defined in the options array when calling pig.enable, so people can extend you script to work with other libraries such as lightboxes

**Comment by schlosser** [comment]
It's a great question.

Because this grid is designed to scroll with long lists of images, HTML elements get added and removed dynamically.

Can you clarify what kind of targeting you're trying to do on the images? Are you hoping to add a click handler to the images or something?

The initial layout sets up the height of the container, but every time you scroll, there are elements being removed and added. When would you like to run your code, and what are you hoping to attach to?

**Comment by mark-rodgers** [comment]
http://brutaldesign.github.io/swipebox/

All I need to do is wrap the IMG tag with an anchor with the class "swipebox"

**Comment by mark-rodgers** [comment]
After the HTML structure is correct I also need to execute this js

```
;( function( $ ) {
	$( '.swipebox' ).swipebox();
} )( jQuery );
```

**Comment by schlosser** [comment]
Do you know if swipebox can handle elements being added at random times? Or do they need to get added all at once? If so, I can add some basic event handling and document this (`onElementInserted`, or something of that nature).

I'll close this issue when I add those hooks, expect them soon!

**Comment by mark-rodgers** [comment]
You know, that's a good question, and I'm not quite sure.

I did however get it working by modifying your code a bit. The code I added in is not very clean and might have a better way to accomplish this. But if you're interested in seeing how I accomplished this, so that maybe you can integrate a more universal way for other people to extend your library to work with lightboxes, here is my fork:

https://github.com/mark-rodgers/pig.js/commit/08c20f02f56204e9b48d3e888c2b3aed96b7f19b

and working demo here: http://photo.marknr.com/galleries

**Comment by schlosser** [comment]
While I think adding some callbacks is a good idea, I'm not sure this swipebox use is general enough to add to the library. I'm going to close this for now but I'm glad you found a solution!
